"""Deletando tarefa

Revision ID: 463931a16310
Revises: 57c5e22ae61b
Create Date: 2026-04-05 14:50:38.920130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463931a16310'
down_revision = '57c5e22ae61b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('deleted')

    # ### end Alembic commands ###
