"""atualizando db

Revision ID: 57c5e22ae61b
Revises: 92c8b9ce29d2
Create Date: 2026-04-05 13:47:54.434351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57c5e22ae61b'
down_revision = '92c8b9ce29d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('urgency', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_time', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fixed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('days_of_week', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('notification_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('notification_sent')
        batch_op.drop_column('days_of_week')
        batch_op.drop_column('fixed')
        batch_op.drop_column('scheduled_time')
        batch_op.drop_column('weight')
        batch_op.drop_column('duration')
        batch_op.drop_column('urgency')
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
